wandb_version: 1

algorithm:
  desc: null
  value: auto
leaf_size:
  desc: null
  value: 30
metric:
  desc: null
  value: minkowski
metric_params:
  desc: null
  value: null
n_jobs:
  desc: null
  value: null
n_neighbors:
  desc: null
  value: 5
p:
  desc: null
  value: 2
weights:
  desc: null
  value: distance
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.15.12
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1699188761.082714
    t:
      1:
      - 5
      - 53
      - 55
      - 105
      2:
      - 5
      - 53
      - 55
      - 105
      3:
      - 13
      - 16
      - 23
      4: 3.11.5
      5: 0.15.12
      8:
      - 2
      - 3
      - 5
      10:
      - 5
      13: windows-amd64
    viz:
      confusion_matrix:
        id: wandb/confusion_matrix/v1
        historyFieldSettings:
          x-axis: _step
          key: confusion_matrix
      class_proportions:
        id: wandb/class_proportions/v1
        historyFieldSettings:
          x-axis: _step
          key: class_proportions
      roc:
        id: wandb/roc/v1
        historyFieldSettings:
          x-axis: _step
          key: roc
      precision_recall:
        id: wandb/pr_curve/v1
        historyFieldSettings:
          x-axis: _step
          key: precision_recall
