wandb_version: 1

algorithm:
  desc: null
  value: auto
leaf_size:
  desc: null
  value: 30
metric:
  desc: null
  value: minkowski
metric_params:
  desc: null
  value: null
n_jobs:
  desc: null
  value: null
n_neighbors:
  desc: null
  value: 5
p:
  desc: null
  value: 2
weights:
  desc: null
  value: uniform
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.15.12
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1699187199.905241
    t:
      1:
      - 5
      - 53
      - 55
      - 105
      2:
      - 5
      - 53
      - 55
      - 105
      3:
      - 13
      - 16
      - 23
      4: 3.11.5
      5: 0.15.12
      8:
      - 2
      - 3
      - 5
      13: windows-amd64
